CREATE TABLE "accounts" (
	"account_id" text PRIMARY KEY NOT NULL,
	"email" text NOT NULL,
	"role" text NOT NULL,
	"display_name" text NOT NULL,
	"active" boolean DEFAULT true NOT NULL,
	"password_hash" text,
	"failed_login_count" integer DEFAULT 0 NOT NULL,
	"locked_until" text,
	"student_id" integer,
	"supervisor_id" integer,
	"created_at" text NOT NULL,
	CONSTRAINT "accounts_email_unique" UNIQUE("email")
);
--> statement-breakpoint
CREATE TABLE "allocation_runs" (
	"run_id" text PRIMARY KEY NOT NULL,
	"algorithm" text NOT NULL,
	"label" text NOT NULL,
	"created_at" text NOT NULL,
	"published" boolean DEFAULT false NOT NULL,
	"instance_size" integer NOT NULL,
	"runtime_ms" integer,
	"params" jsonb,
	"cohort_id" integer
);
--> statement-breakpoint
CREATE TABLE "allocations" (
	"allocation_id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "allocations_allocation_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"run_id" text NOT NULL,
	"algorithm" text NOT NULL,
	"student_id" integer NOT NULL,
	"supervisor_id" integer NOT NULL,
	"objective_score" real,
	"created_at" text NOT NULL
);
--> statement-breakpoint
CREATE TABLE "at_risk_flags" (
	"flag_id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "at_risk_flags_flag_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"student_id" integer NOT NULL,
	"rule_code" text NOT NULL,
	"reason" text NOT NULL,
	"raised_at" text NOT NULL,
	"cleared_at" text,
	"reviewed_at" text,
	"reviewed_by" text,
	"cleared_note" text
);
--> statement-breakpoint
CREATE TABLE "audit_log" (
	"entry_id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "audit_log_entry_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"occurred_at" text NOT NULL,
	"event_type" text NOT NULL,
	"actor_email" text NOT NULL,
	"detail" text NOT NULL
);
--> statement-breakpoint
CREATE TABLE "cohorts" (
	"cohort_id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "cohorts_cohort_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"label" text NOT NULL,
	"imported_at" text NOT NULL,
	"source_file" text,
	"active" boolean DEFAULT false NOT NULL,
	CONSTRAINT "cohorts_label_unique" UNIQUE("label")
);
--> statement-breakpoint
CREATE TABLE "meetings" (
	"meeting_id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "meetings_meeting_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"student_id" integer NOT NULL,
	"supervisor_id" integer NOT NULL,
	"scheduled_at" text NOT NULL,
	"held" integer DEFAULT 0 NOT NULL,
	"notes" text,
	"log_file_name" text,
	"log_file_type" text,
	"log_file_data" text
);
--> statement-breakpoint
CREATE TABLE "milestones" (
	"milestone_id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "milestones_milestone_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"student_id" integer NOT NULL,
	"title" text NOT NULL,
	"description" text,
	"due_date" text NOT NULL,
	"status" text NOT NULL,
	"created_at" text NOT NULL,
	"attachment_name" text,
	"attachment_type" text,
	"attachment_data" text
);
--> statement-breakpoint
CREATE TABLE "preference_window" (
	"id" integer PRIMARY KEY DEFAULT 1 NOT NULL,
	"is_open" boolean NOT NULL,
	"opens_at" text NOT NULL,
	"closes_at" text NOT NULL
);
--> statement-breakpoint
CREATE TABLE "research_areas" (
	"area_id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "research_areas_area_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"code" text NOT NULL,
	"name" text NOT NULL,
	"description" text,
	CONSTRAINT "research_areas_code_unique" UNIQUE("code"),
	CONSTRAINT "research_areas_name_unique" UNIQUE("name")
);
--> statement-breakpoint
CREATE TABLE "sprints" (
	"sprint_id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "sprints_sprint_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"student_id" integer NOT NULL,
	"name" text NOT NULL,
	"goal" text,
	"start_date" text NOT NULL,
	"end_date" text NOT NULL
);
--> statement-breakpoint
CREATE TABLE "student_interests" (
	"student_id" integer NOT NULL,
	"area_id" integer NOT NULL,
	"rank" integer NOT NULL,
	CONSTRAINT "student_interests_student_id_area_id_pk" PRIMARY KEY("student_id","area_id")
);
--> statement-breakpoint
CREATE TABLE "student_preferences" (
	"student_id" integer NOT NULL,
	"supervisor_id" integer NOT NULL,
	"rank" integer NOT NULL,
	CONSTRAINT "student_preferences_student_id_rank_pk" PRIMARY KEY("student_id","rank")
);
--> statement-breakpoint
CREATE TABLE "students" (
	"student_id" integer PRIMARY KEY NOT NULL,
	"first_name" text NOT NULL,
	"last_name" text NOT NULL,
	"email" text NOT NULL,
	"programme" text NOT NULL,
	"mode" text NOT NULL,
	"entry_year" integer NOT NULL,
	"entry_qualification" text NOT NULL,
	"prior_avg_mark" real NOT NULL,
	"created_at" text NOT NULL,
	"cohort_id" integer,
	CONSTRAINT "students_email_unique" UNIQUE("email")
);
--> statement-breakpoint
CREATE TABLE "supervisor_expertise" (
	"supervisor_id" integer NOT NULL,
	"area_id" integer NOT NULL,
	"proficiency" integer NOT NULL,
	CONSTRAINT "supervisor_expertise_supervisor_id_area_id_pk" PRIMARY KEY("supervisor_id","area_id")
);
--> statement-breakpoint
CREATE TABLE "supervisor_preferences" (
	"supervisor_id" integer NOT NULL,
	"student_id" integer NOT NULL,
	"score" real NOT NULL,
	CONSTRAINT "supervisor_preferences_supervisor_id_student_id_pk" PRIMARY KEY("supervisor_id","student_id")
);
--> statement-breakpoint
CREATE TABLE "supervisors" (
	"supervisor_id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "supervisors_supervisor_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"title" text NOT NULL,
	"first_name" text NOT NULL,
	"last_name" text NOT NULL,
	"email" text NOT NULL,
	"seniority" text NOT NULL,
	"fte" real NOT NULL,
	"quota_min" integer NOT NULL,
	"quota_max" integer NOT NULL,
	"created_at" text NOT NULL,
	CONSTRAINT "supervisors_email_unique" UNIQUE("email")
);
--> statement-breakpoint
CREATE TABLE "tasks" (
	"task_id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "tasks_task_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"sprint_id" integer,
	"milestone_id" integer,
	"student_id" integer NOT NULL,
	"title" text NOT NULL,
	"priority" text NOT NULL,
	"status" text NOT NULL,
	"created_at" text NOT NULL,
	"updated_at" text
);
--> statement-breakpoint
ALTER TABLE "accounts" ADD CONSTRAINT "accounts_student_id_students_student_id_fk" FOREIGN KEY ("student_id") REFERENCES "public"."students"("student_id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "accounts" ADD CONSTRAINT "accounts_supervisor_id_supervisors_supervisor_id_fk" FOREIGN KEY ("supervisor_id") REFERENCES "public"."supervisors"("supervisor_id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "allocation_runs" ADD CONSTRAINT "allocation_runs_cohort_id_cohorts_cohort_id_fk" FOREIGN KEY ("cohort_id") REFERENCES "public"."cohorts"("cohort_id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "allocations" ADD CONSTRAINT "allocations_run_id_allocation_runs_run_id_fk" FOREIGN KEY ("run_id") REFERENCES "public"."allocation_runs"("run_id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "allocations" ADD CONSTRAINT "allocations_student_id_students_student_id_fk" FOREIGN KEY ("student_id") REFERENCES "public"."students"("student_id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "allocations" ADD CONSTRAINT "allocations_supervisor_id_supervisors_supervisor_id_fk" FOREIGN KEY ("supervisor_id") REFERENCES "public"."supervisors"("supervisor_id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "at_risk_flags" ADD CONSTRAINT "at_risk_flags_student_id_students_student_id_fk" FOREIGN KEY ("student_id") REFERENCES "public"."students"("student_id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "meetings" ADD CONSTRAINT "meetings_student_id_students_student_id_fk" FOREIGN KEY ("student_id") REFERENCES "public"."students"("student_id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "meetings" ADD CONSTRAINT "meetings_supervisor_id_supervisors_supervisor_id_fk" FOREIGN KEY ("supervisor_id") REFERENCES "public"."supervisors"("supervisor_id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "milestones" ADD CONSTRAINT "milestones_student_id_students_student_id_fk" FOREIGN KEY ("student_id") REFERENCES "public"."students"("student_id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "sprints" ADD CONSTRAINT "sprints_student_id_students_student_id_fk" FOREIGN KEY ("student_id") REFERENCES "public"."students"("student_id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "student_interests" ADD CONSTRAINT "student_interests_student_id_students_student_id_fk" FOREIGN KEY ("student_id") REFERENCES "public"."students"("student_id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "student_interests" ADD CONSTRAINT "student_interests_area_id_research_areas_area_id_fk" FOREIGN KEY ("area_id") REFERENCES "public"."research_areas"("area_id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "student_preferences" ADD CONSTRAINT "student_preferences_student_id_students_student_id_fk" FOREIGN KEY ("student_id") REFERENCES "public"."students"("student_id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "student_preferences" ADD CONSTRAINT "student_preferences_supervisor_id_supervisors_supervisor_id_fk" FOREIGN KEY ("supervisor_id") REFERENCES "public"."supervisors"("supervisor_id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "students" ADD CONSTRAINT "students_cohort_id_cohorts_cohort_id_fk" FOREIGN KEY ("cohort_id") REFERENCES "public"."cohorts"("cohort_id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "supervisor_expertise" ADD CONSTRAINT "supervisor_expertise_supervisor_id_supervisors_supervisor_id_fk" FOREIGN KEY ("supervisor_id") REFERENCES "public"."supervisors"("supervisor_id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "supervisor_expertise" ADD CONSTRAINT "supervisor_expertise_area_id_research_areas_area_id_fk" FOREIGN KEY ("area_id") REFERENCES "public"."research_areas"("area_id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "supervisor_preferences" ADD CONSTRAINT "supervisor_preferences_supervisor_id_supervisors_supervisor_id_fk" FOREIGN KEY ("supervisor_id") REFERENCES "public"."supervisors"("supervisor_id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "supervisor_preferences" ADD CONSTRAINT "supervisor_preferences_student_id_students_student_id_fk" FOREIGN KEY ("student_id") REFERENCES "public"."students"("student_id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "tasks" ADD CONSTRAINT "tasks_sprint_id_sprints_sprint_id_fk" FOREIGN KEY ("sprint_id") REFERENCES "public"."sprints"("sprint_id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "tasks" ADD CONSTRAINT "tasks_milestone_id_milestones_milestone_id_fk" FOREIGN KEY ("milestone_id") REFERENCES "public"."milestones"("milestone_id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "tasks" ADD CONSTRAINT "tasks_student_id_students_student_id_fk" FOREIGN KEY ("student_id") REFERENCES "public"."students"("student_id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
CREATE UNIQUE INDEX "one_published_run" ON "allocation_runs" USING btree ("published") WHERE "allocation_runs"."published" = true;--> statement-breakpoint
CREATE UNIQUE INDEX "allocation_run_student" ON "allocations" USING btree ("run_id","student_id");--> statement-breakpoint
CREATE INDEX "allocation_student" ON "allocations" USING btree ("student_id");--> statement-breakpoint
CREATE INDEX "allocation_supervisor" ON "allocations" USING btree ("supervisor_id");--> statement-breakpoint
CREATE INDEX "flag_student" ON "at_risk_flags" USING btree ("student_id");--> statement-breakpoint
CREATE INDEX "meeting_student" ON "meetings" USING btree ("student_id");--> statement-breakpoint
CREATE INDEX "meeting_supervisor" ON "meetings" USING btree ("supervisor_id");--> statement-breakpoint
CREATE INDEX "milestone_student" ON "milestones" USING btree ("student_id");--> statement-breakpoint
CREATE INDEX "sprint_student" ON "sprints" USING btree ("student_id");--> statement-breakpoint
CREATE UNIQUE INDEX "student_pref_pair" ON "student_preferences" USING btree ("student_id","supervisor_id");--> statement-breakpoint
CREATE INDEX "student_pref_supervisor" ON "student_preferences" USING btree ("supervisor_id");--> statement-breakpoint
CREATE INDEX "student_cohort" ON "students" USING btree ("cohort_id");--> statement-breakpoint
CREATE INDEX "task_student" ON "tasks" USING btree ("student_id");